using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Intex.DAL;
using Intex.Models;

namespace Intex.Controllers
{
    public class InvoicesController : AuthorizedController
    {
        private NorthwestContext db = new NorthwestContext();
        public static decimal subtotal;
        

        //Displays all of the invoices that the customer has
        public ActionResult Index()
        {
            Login name = new Login();
            name = db.Login.Find(User.Identity.Name);
            int nameID = name.ClientID;

            //Queries the databases for all invoices from a certain customer
            IEnumerable<Invoice> theInvoices = db.Database.SqlQuery<Invoice>("SELECT * FROM Invoice WHERE ClientID = " + nameID + " ORDER BY DueDate DESC;");
            List<string> ddates = new List<string>();
            List<string> edates = new List<string>();

            //Adds the dates into lists so that they can be displayed without the time
            foreach (var item in theInvoices)
            {
                ddates.Add(item.DueDate.ToShortDateString());
                edates.Add(item.EarlyDate.ToShortDateString());
            }
            ViewBag.ddates = ddates;
            ViewBag.edates = edates;
            return View(theInvoices.ToList());
        }

        
        //Displays the current balance that the customer owes on the account.
        public ActionResult Create()
        {
            Login theClient = db.Login.Find(User.Identity.Name);
            int clientNum = theClient.ClientID;
            Client ourClient = new Client();
            ourClient = db.Client.Find(clientNum);

            //Sees if the Customer has a balance already. If not it will calculate balance
            //by the amount due on each invoice
            IEnumerable<Invoice> theInvoices;
            if (ourClient.Balance == 0 || ourClient.Balance == null)
            {
                theInvoices = db.Database.SqlQuery<Invoice>("SELECT * FROM Invoice WHERE PaymentStatus != 'Paid'");
                subtotal = 0;
                foreach (var item in theInvoices)
                {
                    subtotal += item.TotalMatCost;
                }
                var sql = "UPDATE Client SET Balance = @subtotal WHERE ClientID = @clientID;";
                db.Database.ExecuteSqlCommand(sql, new SqlParameter("@clientID", clientNum), new SqlParameter("@subtotal", subtotal));

                ViewBag.InvoiceOutput = subtotal;
            }
            else
            {
                Client newClient = new Client();
                newClient = db.Client.Find(clientNum);

                ViewBag.InvoiceOutput = newClient.Balance;
            }
            return View();
        }

        //Displays the Payment page and lets the customer pay an amount
        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }

        //Takes the amount the customer wants to pay and UPDATES the balance with that amount
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormCollection paymentAmount)
        {
            Login name = new Login();
            name = db.Login.Find(User.Identity.Name);
            Client theClient = new Client();
            theClient = db.Client.Find(name.ClientID);
            if (paymentAmount == null)
            {
                return HttpNotFound();
            }
            else
            {
                decimal payment = Convert.ToDecimal(paymentAmount["Payment Amount"]);
                decimal? difference = theClient.Balance - payment;

                var sql = "UPDATE Client SET Balance = @subtotal WHERE ClientID = @clientID;";
                db.Database.ExecuteSqlCommand(sql, new SqlParameter("@clientID", name.ClientID), new SqlParameter("@subtotal", difference));

                return RedirectToAction("Create");
            }
        }

        //We don't know what this does. It was autogenerated.
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
